[versions]
bignum = "0.3.10"
kotlin = "2.0.0"

[libraries]
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }